const players = [
  { name: "Ruturaj Gaikwad", run: 0 },
  { name: "Dewald Brevis", run: 0 },
  { name: "Ayush Mhatre", run: 0 },
  { name: "Matthew Short", run: 0 },
  { name: "Sarfaraz Khan", run: 0 },
  { name: "Shivam Dube", run: 0 },
  { name: "Ramakrishna Ghosh", run: 0 },
  { name: "Jamie Overton", run: 0 },
  { name: "Anshul Kamboj", run: 0 },
  { name: "Zakary Foulkes", run: 0 },
  { name: "MS Dhoni", run: 0 },
  { name: "Urvil Patel", run: 0 },
  { name: "Sanju Samson", run: 0 },
  { name: "Kartik Sharma", run: 0 },
  { name: "Shreyas Gopal", run: 0 },
  { name: "Khaleel Ahmed", run: 0 },
  { name: "Gurjapneet Singh", run: 0 },
  { name: "Mukesh Choudhary", run: 0 },
  { name: "Noor Ahmad", run: 0 },
  { name: "Prashant Veer", run: 0 },
  { name: "Akeal Hosein", run: 0 },
  { name: "Matt Henry", run: 0 },
  { name: "Rahul Chahar", run: 0 },
  { name: "Karun Nair", run: 0 },
  { name: "Nitish Rana", run: 0 },
  { name: "Sameer Rizvi", run: 0 },
  { name: "David Miller", run: 0 },
  { name: "Ben Duckett", run: 0 },
  { name: "Pathum Nissanka", run: 0 },
  { name: "Sahil Parakh", run: 0 },
  { name: "Prithvi Shaw", run: 0 },
  { name: "Ashutosh Sharma", run: 0 },
  { name: "Axar Patel", run: 0 },
  { name: "Ajay Jadav Mandal", run: 0 },
  { name: "Madhav Tiwari", run: 0 },
  { name: "Tripurana Vijay", run: 0 },
  { name: "Auqib Nabi Dar", run: 0 },
  { name: "Abishek Porel", run: 0 },
  { name: "KL Rahul", run: 0 },
  { name: "Tristan Stubbs", run: 0 },
  { name: "Dushmantha Chameera", run: 0 },
  { name: "Kuldeep Yadav", run: 0 },
  { name: "Mukesh Kumar", run: 0 },
  { name: "T Natarajan", run: 0 },
  { name: "Vipraj Nigam", run: 0 },
  { name: "Mitchell Starc", run: 0 },
  { name: "Lungi Ngidi", run: 0 },
  { name: "Kyle Jamieson", run: 0 },
  { name: "Shubman Gill", run: 0 },
  { name: "M Shahrukh Khan", run: 0 },
  { name: "Sai Sudharsan", run: 0 },
  { name: "Nishant Sindhu", run: 0 },
  { name: "Rashid Khan", run: 0 },
  { name: "Manav Suthar", run: 0 },
  { name: "Rahul Tewatia", run: 0 },
  { name: "Washington Sundar", run: 0 },
  { name: "Arshad Khan", run: 0 },
  { name: "Ravisrinivasan Sai Kishore", run: 0 },
  { name: "Jason Holder", run: 0 },
  { name: "Anuj Rawat", run: 0 },
  { name: "Jos Buttler", run: 0 },
  { name: "Kumar Kushagra", run: 0 },
  { name: "Glenn Phillips", run: 0 },
  { name: "Tom Banton", run: 0 },
  { name: "Gurnoor Brar", run: 0 },
  { name: "Mohammed Siraj", run: 0 },
  { name: "Prasidh Krishna", run: 0 },
  { name: "Kagiso Rabada", run: 0 },
  { name: "Jayant Yadav", run: 0 },
  { name: "Ishant Sharma", run: 0 },
  { name: "Ashok Sharma", run: 0 },
  { name: "Prithvi Raj Yarra", run: 0 },
  { name: "Luke Wood", run: 0 },
  { name: "Rajat Patidar", run: 0 },
  { name: "Tim David", run: 0 },
  { name: "Virat Kohli", run: 0 },
  { name: "Devdutt Padikkal", run: 0 },
  { name: "Jacob Bethell", run: 0 },
  { name: "Krunal Pandya", run: 0 },
  { name: "Venkatesh Iyer", run: 0 },
  { name: "Vihaan Malhotra", run: 0 },
  { name: "Romario Shepherd", run: 0 },
  { name: "Mangesh Yadav", run: 0 },
  { name: "Kanishk Chouhan", run: 0 },
  { name: "Satvik Deswal", run: 0 },
  { name: "Philip Salt", run: 0 },
  { name: "Jitesh Sharma", run: 0 },
  { name: "Jordan Cox", run: 0 },
  { name: "Abhinandan Singh", run: 0 },
  { name: "Josh Hazlewood", run: 0 },
  { name: "Rasikh Salam Dar", run: 0 },
  { name: "Bhuvneshwar Kumar", run: 0 },
  { name: "Suyash Sharma", run: 0 },
  { name: "Swapnil Singh", run: 0 },
  { name: "Yash Dayal", run: 0 },
  { name: "Nuwan Thushara", run: 0 },
  { name: "Jacob Duffy", run: 0 },
  { name: "Vicky Ostwal", run: 0 },
  { name: "Shreyas Iyer", run: 0 },
  { name: "Priyansh Arya", run: 0 },
  { name: "Pyla Avinash", run: 0 },
  { name: "Harnoor Singh", run: 0 },
  { name: "Nehal Wadhera", run: 0 },
  { name: "Mitchell Owen", run: 0 },
  { name: "Musheer Khan", run: 0 },
  { name: "Shashank Singh", run: 0 },
  { name: "Marcus Stoinis", run: 0 },
  { name: "Suryansh Shedge", run: 0 },
  { name: "Cooper Connolly", run: 0 },
  { name: "Azmatullah Omarzai", run: 0 },
  { name: "Marco Jansen", run: 0 },
  { name: "Praveen Dubey", run: 0 },
  { name: "Prabhsimran Singh", run: 0 },
  { name: "Vishnu Vinod", run: 0 },
  { name: "Arshdeep Singh", run: 0 },
  { name: "Xavier Bartlett", run: 0 },
  { name: "Yuzvendra Chahal", run: 0 },
  { name: "Lockie Ferguson", run: 0 },
  { name: "Harpreet Brar", run: 0 },
  { name: "Vijaykumar Vyshak", run: 0 },
  { name: "Yash Thakur", run: 0 },
  { name: "Ben Dwarshuis", run: 0 },
  { name: "Vishal Nishad", run: 0 },
  { name: "Ajinkya Rahane", run: 0 },
  { name: "Manish Pandey", run: 0 },
  { name: "Rovman Powell", run: 0 },
  { name: "Angkrish Raghuvanshi", run: 0 },
  { name: "Rinku Singh", run: 0 },
  { name: "Finn Allen", run: 0 },
  { name: "Rahul Tripathi", run: 0 },
  { name: "Sarthak Ranjan", run: 0 },
  { name: "Ramandeep Singh", run: 0 },
  { name: "Anukul Roy", run: 0 },
  { name: "Cameron Green", run: 0 },
  { name: "Rachin Ravindra", run: 0 },
  { name: "Sunil Narine", run: 0 },
  { name: "Daksh Kamra", run: 0 },
  { name: "Tim Seifert", run: 0 },
  { name: "Tejasvi Dahiya", run: 0 },
  { name: "Vaibhav Arora", run: 0 },
  { name: "Umran Malik", run: 0 },
  { name: "Varun Chakaravarthy", run: 0 },
  { name: "Prashant Solanki", run: 0 },
  { name: "Kartik Tyagi", run: 0 },
  { name: "Matheesha Pathirana", run: 0 },
  { name: "Blessing Muzarabani", run: 0 },
  { name: "Saurabh Dubey", run: 0 },
  { name: "Travis Head", run: 0 },
  { name: "Smaran Ravichandran", run: 0 },
  { name: "Aniket Verma", run: 0 },
  { name: "Abhishek Sharma", run: 0 },
  { name: "Kamindu Mendis", run: 0 },
  { name: "Nitish Kumar Reddy", run: 0 },
  { name: "Liam Livingstone", run: 0 },
  { name: "Harsh Dubey", run: 0 },
  { name: "Shivang Kumar", run: 0 },
  { name: "Ishan Kishan", run: 0 },
  { name: "Heinrich Klaasen", run: 0 },
  { name: "Salil Arora", run: 0 },
  { name: "Brydon Carse", run: 0 },
  { name: "Pat Cummins", run: 0 },
  { name: "Eshan Malinga", run: 0 },
  { name: "Jaydev Unadkat", run: 0 },
  { name: "Harshal Patel", run: 0 },
  { name: "Zeeshan Ansari", run: 0 },
  { name: "Sakib Hussain", run: 0 },
  { name: "Onkar Tukaram Tarmale", run: 0 },
  { name: "Amit Kumar", run: 0 },
  { name: "Praful Hinge", run: 0 },
  { name: "Krains Fuletra", run: 0 },
  { name: "Shivam Mavi", run: 0 },
  { name: "Shubham Dubey", run: 0 },
  { name: "Shimron Hetmyer", run: 0 },
  { name: "Yashasvi Jaiswal", run: 0 },
  { name: "Vaibhav Sooryavanshi", run: 0 },
  { name: "Aman Rao Perala", run: 0 },
  { name: "Riyan Parag", run: 0 },
  { name: "Dasun Shanaka", run: 0 },
  { name: "Ravindra Jadeja", run: 0 },
  { name: "Dhruv Jurel", run: 0 },
  { name: "Lhuan-dre Pretorius", run: 0 },
  { name: "Donovan Ferreira", run: 0 },
  { name: "Ravi Singh", run: 0 },
  { name: "Jofra Archer", run: 0 },
  { name: "Nandre Burger", run: 0 },
  { name: "Tushar Deshpande", run: 0 },
  { name: "Kwena Maphaka", run: 0 },
  { name: "Sandeep Sharma", run: 0 },
  { name: "Yudhvir Singh Charak", run: 0 },
  { name: "Vignesh Puthur", run: 0 },
  { name: "Yash Raj Punja", run: 0 },
  { name: "Sushant Mishra", run: 0 },
  { name: "Ravi Bishnoi", run: 0 },
  { name: "Brijesh Sharma", run: 0 },
  { name: "Adam Milne", run: 0 },
  { name: "Kuldeep Sen", run: 0 },
  { name: "Himmat Singh", run: 0 },
  { name: "Aiden Markram", run: 0 },
  { name: "Akshat Raghuwanshi", run: 0 },
  { name: "Abdul Samad", run: 0 },
  { name: "Ayush Badoni", run: 0 },
  { name: "Arshin Kulkarni", run: 0 },
  { name: "Mitchell Marsh", run: 0 },
  { name: "Shahbaz Ahmed", run: 0 },
  { name: "Arjun Sachin Tendulkar", run: 0 },
  { name: "Wanindu Hasaranga", run: 0 },
  { name: "Rishabh Pant", run: 0 },
  { name: "Matthew Breetzke", run: 0 },
  { name: "Nicholas Pooran", run: 0 },
  { name: "Mukul Choudhary", run: 0 },
  { name: "Josh Inglis", run: 0 },
  { name: "Akash Maharaj Singh", run: 0 },
  { name: "Avesh Khan", run: 0 },
  { name: "Mohammed Shami", run: 0 },
  { name: "Prince Yadav", run: 0 },
  { name: "Mohsin Khan", run: 0 },
  { name: "Digvesh Singh Rathi", run: 0 },
  { name: "Manimaran Siddharth", run: 0 },
  { name: "Mayank Prabhu Yadav", run: 0 },
  { name: "Anrich Nortje", run: 0 },
  { name: "Naman Tiwari", run: 0 },
  { name: "Naman Dhir", run: 0 },
  { name: "Rohit Sharma", run: 0 },
  { name: "Suryakumar Yadav", run: 0 },
  { name: "Tilak Varma", run: 0 },
  { name: "Danish Malewar", run: 0 },
  { name: "Sherfane Rutherford", run: 0 },
  { name: "Hardik Pandya", run: 0 },
  { name: "Raj Bawa", run: 0 },
  { name: "Will Jacks", run: 0 },
  { name: "Mayank Rawat", run: 0 },
  { name: "Corbin Bosch", run: 0 },
  { name: "Mitchell Santner", run: 0 },
  { name: "Shardul Thakur", run: 0 },
  { name: "Atharva Ankolekar", run: 0 },
  { name: "Robin Minz", run: 0 },
  { name: "Ryan Rickelton", run: 0 },
  { name: "Quinton de Kock", run: 0 },
  { name: "Trent Boult", run: 0 },
  { name: "Ashwani Kumar", run: 0 },
  { name: "Jasprit Bumrah", run: 0 },
  { name: "Deepak Chahar", run: 0 },
  { name: "Mayank Markande", run: 0 },
  { name: "AM Ghazanfar", run: 0 },
  { name: "Raghu Sharma", run: 0 },
  { name: "Mohammed Salahuddin Izhar", run: 0 },
];

const Data = require('./models/Data.model');
const Last = require('./models/Last.model');

const uploadPlayers = async () => {
    try {
        const newData = new Data({
            data: players
        });

        const last = new Last({
            last:0
        })


      

        await newData.save();
        await last.save();
        console.log("Players uploaded successfully ✅");

    } catch (error) {
        console.error("Upload error ❌", error);
    }
};

module.exports = uploadPlayers;